db:
  type: 'postgres'
  host: 'localhost'
  port: 5432
  username: 'postgres'
  password: 'postgres'
  database: 'db'
  synchronize: true

server:
  port: 3001
  scheme: 'http'

jwt:
  secret: 'SECRET'
  expiresIn: 1000000

maps:
  key: 'AIzaSyCQg9-Vx2KgFxSkWGujh3_aoklegMvB3Ms'

mail:
  user: 'mail@mail.com'
  password: 'password'
